# This workflow will upload a Python Package to PyPI.

name: Build and publish wheels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.10"]
        os: [arm-ubuntu-22]

    steps:
      - uses: "actions/checkout@v3"
      - name: Create directory
        run: |
          mkdir -p /tmp/grain
          cp -r . /tmp/grain
      - name: Build package
        run: |
          set -xe
          export PYTHON_VERSION=${{ matrix.python-version }}
          export PYTHON_MAJOR_VERSION=$(echo $PYTHON_VERSION | cut -d. -f1)
          export PYTHON_MINOR_VERSION=$(echo $PYTHON_VERSION | cut -d. -f2)
          export BAZEL_VERSION="5.4.0"
          export OUTPUT_DIR="/tmp/grain"
          export SOURCE_DIR="${OUTPUT_DIR}"
          source ${OUTPUT_DIR}/grain/oss/runner_common.sh
          update_bazel_macos ${BAZEL_VERSION}
          bazel --version
          pushd ${OUTPUT_DIR}
          setup_env_vars_py $PYTHON_MAJOR_VERSION $PYTHON_MINOR_VERSION
          install_and_init_pyenv
          install_grain_deps
          bash "${SOURCE_DIR}/grain/oss/build_whl.sh"
          popd
          cp -r /tmp/grain/all_dist/* ${OUTPUT_DIR}/grain/all_dist
      - name: Upload Grain artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-grain-wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: /tmp/grain/**/*.whl
